# Generated by Django 4.0.4 on 2022-05-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_indicator_accomplishment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseline',
            old_name='number_of_items',
            new_name='count',
        ),
        migrations.AlterField(
            model_name='baseline',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baselines', to='api.measurement'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='accomplishment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='api.accomplishment'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='api.indicator'),
        ),
        migrations.AlterField(
            model_name='quarter',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarters', to='api.measurement'),
        ),
        migrations.AlterField(
            model_name='target',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='api.quarter'),
        ),
    ]
